renovate.json

chore(renov): use common SocialGouv config

---

packages/contrib/pages/answer.js

* contrib/pages/answer: fix editor content saving

fix(contrib): editor content saving (#98)

---

db/migrations/knex/20190523114652_expose_questions_table.js

fix(api): expose questions data

---

packages/contrib/pages/admin/answers/index.js
packages/contrib/src/texts.js

fix(admin): answers search input behavior

---

packages/contrib/pages/index.js

feat(contrib): sort answers index by question index & agreement idcc

---

packages/contrib/src/layouts/Menu.js
packages/contrib/src/layouts/__tests__/Menu.test.js
packages/contrib/src/layouts/__tests__/__snapshots__/Header.test.js.snap
packages/contrib/src/layouts/__tests__/__snapshots__/Menu.test.js.snap

feat(contrib): complete help menu

---

packages/contrib/pages/login.js

Salut @ivangabriele on a besoin de faire un changement d'adresse mail, si c'est ok pour toi ce serait cool de faire le déploiement le plus rapidement possible, je viens de me rendre compte que l'autre adresse ne fonctionnait pas...

fix(contrib): homepage email address

---

packages/contrib/package.json
packages/contrib/yarn.lock

This reverts commit b3c81cda7103d648c5068c2903503a97dff8b37f.

revert "fix(deps): update dependency next to v9 (#317)"

---

packages/contrib/jest.config.js
packages/contrib/pages/admin/answers/edit.js
packages/contrib/pages/admin/answers/index.js
packages/contrib/src/actions/answers.js
packages/contrib/src/blocks/AdminAnswer/__tests__/index.test.js
packages/contrib/src/blocks/AdminAnswer/index.js
packages/contrib/src/constants.js
packages/contrib/src/layouts/AdminMain.js
packages/contrib/src/layouts/__tests__/AdminMain.test.js
packages/contrib/src/layouts/__tests__/__snapshots__/AdminMain.test.js.snap
packages/contrib/src/reducers/answers.js
packages/contrib/src/sagas/answers.js
packages/contrib/src/texts.js

feat(admin): add under_review state to answers

---

packages/contrib/src/blocks/AdminAnswer/index.js
packages/contrib/src/libs/customMoment.js

feat(admin): create custom moment lib

---

packages/contrib/pages/admin/answers/index.js

feat(admin): open answers in a new tab

---

packages/contrib/src/blocks/AnswerEditionReferences/__tests__/__snapshots__/index.test.js.snap
packages/contrib/src/blocks/AnswerEditionReferences/index.js

feat(contrib): invert laws & agreement refs in answers edit page

---

packages/contrib/pages/admin/questions/index.js
packages/contrib/src/components/AdminIndex.js

fix(admin): first row width in questions index page

---

packages/contrib/pages/admin/answers/edit.js
packages/contrib/pages/admin/answers/index.js
packages/contrib/src/blocks/AdminAnswer/index.js

feat(admin): add validated answers preview

---

README.md
db/migrations/20190808123135_create_regional_administrator_role.sql
db/migrations/knex/20190808123135_create_regional_administrator_role.js
db/seeds/dev/04-users.js
db/seeds/dev/07-answers.js
features/login.feature
features/support/world/index.js
packages/contrib/pages/_app.js
packages/contrib/pages/admin/users/new.js
packages/contrib/pages/login.js
packages/contrib/src/constants.js
packages/contrib/src/layouts/AdminMenu.js
packages/contrib/src/libs/getCurrentUser.js

feat(admin): add regional administrator role

---

packages/contrib/pages/answers/edit.js
packages/contrib/pages/answers/index.js
packages/contrib/pages/answers/view.js
packages/contrib/server/routes.js
packages/contrib/src/blocks/Answer/index.js
packages/contrib/src/blocks/AnswerEditionHead/__tests__/__snapshots__/index.test.js.snap
packages/contrib/src/blocks/AnswerEditionHead/__tests__/index.test.js
packages/contrib/src/blocks/AnswerEditionHead/index.js
packages/contrib/src/layouts/Main.js

feat(contrib): add validated answers preview

---

packages/contrib/pages/answers/edit.js
packages/contrib/src/blocks/AnswerEditionReferences/List.js
packages/contrib/src/blocks/AnswerEditionReferences/index.js

feat(contrib): add url input in answers agreement references

---

db/migrations/20190905093812_create_tags_categories_table.sql
db/migrations/knex/20190905093812_create_tags_categories_table.js
db/seeds/dev/05-tags.js
packages/contrib/pages/admin/tags-categories/edit.js
packages/contrib/pages/admin/tags-categories/index.js
packages/contrib/pages/admin/tags-categories/new.js
packages/contrib/pages/admin/tags/edit.js
packages/contrib/pages/admin/tags/index.js
packages/contrib/pages/admin/tags/new.js
packages/contrib/server/routes.js
packages/contrib/src/components/AdminIndex.js
packages/contrib/src/layouts/AdminMenu.js
packages/contrib/src/layouts/__tests__/AdminMenu.test.js

feat(admin): add tags categories management

---

packages/contrib/pages/admin/index.js

feat(admin): group per agreement stats by location

---

packages/contrib/pages/answers/view.js

fix(contrib): answers view overflow

---

packages/contrib/package.json
packages/contrib/pages/_app.js
packages/contrib/pages/admin/answers/index.js
packages/contrib/pages/admin/answers/print.js
packages/contrib/pages/admin/generic-answers/print.js
packages/contrib/pages/answers/edit.js
packages/contrib/pages/login.js
packages/contrib/server/routes.js
packages/contrib/src/components/Login.js
packages/contrib/src/elements/ContentTitle.js
packages/contrib/src/elements/__tests__/ContentTitle.test.js
packages/contrib/src/elements/__tests__/__snapshots__/ContentTitle.test.js.snap
packages/contrib/src/layouts/Header.js
packages/contrib/src/layouts/Menu.js
packages/contrib/src/libs/__tests__/customAxios.test.js
packages/contrib/src/libs/__tests__/isAuthenticated.test.js
packages/contrib/src/libs/customAxios.js
packages/contrib/src/libs/getCurrentUser.js
packages/contrib/src/libs/isAuthenticated.js
packages/contrib/src/sagas/answers.js
packages/contrib/src/sagas/comments.js
packages/contrib/yarn.lock

feat(admin): add answers printing

---

packages/contrib/pages/admin/answers/edit.js

feat(admin): add answers state update within edition

---

packages/contrib/pages/admin/index.js
packages/contrib/src/components/AdminIndex.js
packages/contrib/src/components/Table.js

feat(admin): add filterable dashboard stats

---

.prettierrc
CONTRIBUTING.md

docs: add contributing page

---

packages/contrib/pages/admin/answers/index.js
packages/contrib/pages/admin/answers/print.js
packages/contrib/src/actions/answers.js
packages/contrib/src/reducers/answers.js
packages/contrib/src/sagas/answers.js

fix(admin): format answers printed values

---

packages/contrib/pages/admin/index.js

feat(admin): add idcc to dashboard per agreement stats

---

packages/data-filler/scripts/fixUrl.js
packages/data-filler/src/cdtn-api.js
packages/data-filler/src/forms/CCN.js
packages/data-filler/src/forms/components/CDTNReferences.js
packages/data-filler/src/sources.js

backport some upstream fixes : 
- use new kali-data format
- use master CDTN API

fix(data-filler): backport latest fixes

---

.codacy.yml
.github/ISSUE_TEMPLATE/feature.md

enrichissement du template ( // produit)

ci(github): update feature issue template

---

.github/ISSUE_TEMPLATE/improvement.md

enrichissement du template (avec le template produit)

ci(github): update improvement issue template

---

db/migrations/20200226050422_add_answers_references_table_is_skipped_field.sql
db/migrations/knex/20200226050422_add_answers_references_table_is_skipped_field.js
packages/app/pages/admin/legal-references-migration/index.js
packages/app/src/sagas/answers/updateReferences.js

feat(app): allow legal references to be skipped in migration tool

---

packages/app/pages/admin/answers/edit.js

fix(app): link load method in answers edit page

---

package.json
packages/api/package.json
packages/api/src/libs/findAgreementArticles.js
packages/api/src/services/Agreement.js
packages/api/src/services/LaborCode.js
packages/api/src/types.js
packages/app/src/components/LegalReferences/Tag.js
packages/app/src/components/LegalReferences/Tag.style.js
packages/app/src/sagas/legal-references/load.js
yarn.lock

feat(api): add addional texts to legal references

---

packages/app/pages/admin/legal-references-migration/index.js

feat(admin): restrict migrations to published answers

---

package.json
packages/app/package.json
packages/app/src/libs/__tests__/markdown.test.js
packages/app/src/libs/markdown.js
yarn.lock

fix(app): include sub-nested bullets in printed answers

---

packages/app/pages/admin/legal-references-migration/index.js

feat(app): add agreement selection in legal references migration

---

packages/app/pages/admin/answers/edit.js
packages/app/src/components/LegalReferences/Tag.js
packages/app/src/components/LegalReferences/Tag.style.js
packages/app/src/components/LegalReferences/TagEditor.js
packages/app/src/components/LegalReferences/TagEditor.style.js
packages/app/src/components/LegalReferences/index.js
packages/app/src/props/LegalReference.js

feat(app): add other legal references edition

---

features/support/hooks/takeScreenshotOnFailure.js
package.json
packages/app/package.json
packages/app/pages/admin/answers/index.js
yarn.lock

fix(api): fix persistent answers search query

---

packages/app/pages/admin/answers/edit.js
packages/app/src/layouts/AdminMain/__tests__/index.test.js
packages/app/src/layouts/AdminMain/index.js
packages/app/src/layouts/AdminMain/styles.js
packages/app/src/layouts/AdminMenu/__tests__/index.test.js
packages/app/src/layouts/Header/__tests__/index.test.js
packages/app/src/layouts/Header/index.js
packages/app/src/layouts/Main/__tests__/index.test.js
packages/app/src/layouts/Menu/__tests__/index.test.js
packages/app/src/layouts/Menu/index.js

test(app): complete layouts coverage

---

packages/app/pages/admin/legal-references-migration-fix/index.js

fix(app): enable legal references content in migration tool

---

packages/app/src/components/LegalReferences/Tag.style.js

feat(app): allow text selection in legal reference tags

---

packages/app/jest.config.js
packages/app/pages/admin/answers/index.js
packages/app/src/components/Pagination/__tests__/index.test.js
packages/app/src/components/Pagination/index.js
packages/app/src/components/Pagination/index.style.js
packages/app/src/elements/Button.js
packages/app/src/reducers/answers.js

feat(app): restore answers pagination

---

packages/app/pages/admin/answers/edit.js
packages/app/src/components/LegalReferences/Selector.js
packages/app/src/components/LegalReferences/Selector.style.js
packages/app/src/components/LegalReferences/Tag.js
packages/app/src/components/LegalReferences/Tag.style.js
packages/app/src/components/LegalReferences/__tests__/Selector.test.js
packages/app/src/components/LegalReferences/__tests__/index.test.js
packages/app/src/components/LegalReferences/index.js
packages/app/src/components/LegalReferences/index.style.js
packages/app/src/elements/Input.js

feat(app): add agreement selection to legal reference component

---

packages/app/package.json
yarn.lock

This reverts commit 38168cafec151b2cfec1df30d99adf2a9a00bf76.

revert: fix(deps): update dependency unist-util-parents to v2 (#1191)
